TRANSLATIONS = {
    "zh": {
        "page_title": "HPLC 极简可视化",
        "app_title": "HPLC 极简可视化",
        "app_subtitle": "上传您的 HPLC 数据，将自动渲染交互式折线图。",
        "upload_label": "请上传一个或多个 HPLC 数据文件 (CSV, CTX)",
        "example_data_title": "没有数据？可以先试用内置示例。",
        "load_examples_btn": "加载示例数据",
        "download_examples_btn": "下载示例 ZIP",
        "clear_files_btn": "🧹 一键清空所有导入文件",
        "imported_files": "### 已导入文件",
        "remove_file_help": "从本次绘图中移除",
        "parse_error": "解析文件前置发生错误: {}",
        "plot_error": "处理文件时发生错误: {}",
        
        "sidebar_header": "🎨 论文排版设置",
        "lang_title": "🌐 语言 / Language",
        "palette_title": "##### 1. 选择全局配色包",
        "palette_select": "自动为多条曲线分配颜色",
        "y_offset_title": "##### 2. Y轴错开堆叠 (Waterfall)",
        "y_offset_check": "启用均匀错开 (防止曲线重叠)",
        "y_offset_input": "堆叠间距 (Y-Offset)",
        "line_width_title": "##### 3. 设置全局线条粗细",
        "line_width_slider": "统一调节线宽",
        "display_settings_title": "##### 4. 辅助显示设置",
        "show_legend": "在图表中显示注释图例",
        "show_y_axis": "显示 Y 轴及刻度",
        "sample_label_position": "样品名显示位置",
        "sample_label_none": "不在曲线上显示",
        "sample_label_left": "显示在线左端",
        "sample_label_right": "显示在线右端",
        "sample_label_font_size": "样品名字号",
        "x_range_slider": "裁剪/缩放时间轴 (X轴范围)",
        "plot_width_mode": "图幅宽度",
        "plot_width_auto": "按时间范围自动调整",
        "plot_width_stretch": "铺满页面",
        "plot_width_custom": "自定义",
        "plot_width_custom_value": "自定义宽度 (px)",
        "interaction_title": "##### 5. 交互与标记 (点击/框选)",
        "sidebar_colored_title": "**🖌️ 已染色的峰面积:**",
        "clear_colors_btn": "🧹 清除所有染色",
        "delete_btn": "🗑️",
        "clear_marks_btn": "🧹 清除所有标记线",
        "view_raw_data": "查看 {} 原始数据",
        "download_svg_btn": "⬇ 下载 SVG 矢量图",
        "footer_made_by": "Made by 拒绝峰型拖尾、只想早点下班的小J",
        "footer_support": "👍 觉得好用？",
        "axis_time": "Time (min)",
        "axis_intensity": "Intensity"
    },
    "en": {
        "page_title": "HPLC Minimalist Plot",
        "app_title": "HPLC Minimalist Plot",
        "app_subtitle": "Upload your HPLC data to automatically render an interactive line chart.",
        "upload_label": "Upload one or more HPLC data files (CSV, CTX)",
        "example_data_title": "No data yet? Try the built-in examples.",
        "load_examples_btn": "Load example data",
        "download_examples_btn": "Download example ZIP",
        "clear_files_btn": "🧹 Clear all imported files",
        "imported_files": "### Imported Files",
        "remove_file_help": "Remove from this plot",
        "parse_error": "Error during file parsing: {}",
        "plot_error": "Error during plot rendering: {}",
        
        "sidebar_header": "🎨 Publication Styling",
        "lang_title": "🌐 Language",
        "palette_title": "##### 1. Global Color Palette",
        "palette_select": "Auto-assign colors for multiple curves",
        "y_offset_title": "##### 2. Y-Axis Stacking (Waterfall)",
        "y_offset_check": "Enable even spacing (prevent overlapping)",
        "y_offset_input": "Stacking Spacing (Y-Offset)",
        "line_width_title": "##### 3. Global Line Width",
        "line_width_slider": "Adjust line width uniformly",
        "display_settings_title": "##### 4. Display Settings",
        "show_legend": "Show legend in the chart",
        "show_y_axis": "Show Y-axis and ticks",
        "sample_label_position": "Sample name position",
        "sample_label_none": "Do not show on curves",
        "sample_label_left": "Show at left edge",
        "sample_label_right": "Show at right edge",
        "sample_label_font_size": "Sample name font size",
        "x_range_slider": "Crop/Zoom Timeline (X-Axis Range)",
        "plot_width_mode": "Figure width",
        "plot_width_auto": "Auto by time range",
        "plot_width_stretch": "Fill page width",
        "plot_width_custom": "Custom",
        "plot_width_custom_value": "Custom width (px)",
        "interaction_title": "##### 5. Interaction & Marking (Click/Box)",
        "sidebar_colored_title": "**🖌️ Colored Peak Areas:**",
        "clear_colors_btn": "🧹 Clear all colors",
        "delete_btn": "🗑️",
        "clear_marks_btn": "🧹 Clear all marked lines",
        "view_raw_data": "View raw data for {}",
        "download_svg_btn": "⬇ Download SVG figure",
        "footer_made_by": "Made by J, fleeing the lab exactly on time.",
        "footer_support": "👍 Like this tool?",
        "axis_time": "Time (min)",
        "axis_intensity": "Intensity"
    },
    "jp": {
        "page_title": "HPLC シンプル可視化",
        "app_title": "HPLC シンプル可視化",
        "app_subtitle": "HPLCデータをアップロードすると、インタラクティブな折れ线グラフが自动的に描画されます。",
        "upload_label": "HPLCデータファイル（CSV, CTX）をアップロードしてください",
        "example_data_title": "データがない場合は、内蔵サンプルを試せます。",
        "load_examples_btn": "サンプルデータを読み込む",
        "download_examples_btn": "サンプル ZIP をダウンロード",
        "clear_files_btn": "🧹 すべてのインポートファイルをクリア",
        "imported_files": "### インポート済みのファイル",
        "remove_file_help": "このプロットから削除",
        "parse_error": "ファイルの解析中にエラーが発生しました: {}",
        "plot_error": "プロットの描画中にエラーが発生しました: {}",
        
        "sidebar_header": "🎨 论文フォーマット设定",
        "lang_title": "🌐 言语 / Language",
        "palette_title": "##### 1. グローバルカラーパレット",
        "palette_select": "复数の曲线に色を自动割り当て",
        "y_offset_title": "##### 2. Y轴のスタッキング",
        "y_offset_check": "均等な间隔を有効にする（重なりを防止）",
        "y_offset_input": "スタッキング间隔（Y-オフセット）",
        "line_width_title": "##### 3. グローバル线の太さ",
        "line_width_slider": "线の太さを均一に调整",
        "display_settings_title": "##### 4. 表示设定",
        "show_legend": "チャートに凡例を表示する",
        "show_y_axis": "Y轴と目盛りを表示する",
        "sample_label_position": "サンプル名の表示位置",
        "sample_label_none": "曲線上に表示しない",
        "sample_label_left": "左端に表示",
        "sample_label_right": "右端に表示",
        "sample_label_font_size": "サンプル名の文字サイズ",
        "x_range_slider": "タイムラインのトリミング/ズーム（X轴の范囲）",
        "plot_width_mode": "図の幅",
        "plot_width_auto": "時間範囲に合わせて自動調整",
        "plot_width_stretch": "ページ幅いっぱい",
        "plot_width_custom": "カスタム",
        "plot_width_custom_value": "カスタム幅 (px)",
        "interaction_title": "##### 5. インタラクション (クリック/ドラッグ)",
        "sidebar_colored_title": "**🖌️ 着色されたピーク面積:**",
        "clear_colors_btn": "🧹 すべての着色をクリア",
        "delete_btn": "🗑️",
        "clear_marks_btn": "🧹 すべてのマークされた線をクリア",
        "view_raw_data": "{} の生データを表示",
        "download_svg_btn": "⬇ SVG 図をダウンロード",
        "footer_made_by": "定時退社を全力で夢見るKより",
        "footer_support": "👍 気に入りましたか？",
        "axis_time": "Time (min)",
        "axis_intensity": "Intensity"
    }
}

def get_text(lang, key, *args):
    text = TRANSLATIONS.get(lang, TRANSLATIONS["zh"]).get(key, key)
    if args:
        return text.format(*args)
    return text
