TRANSLATIONS = {
    "zh": {
        "page_title": "HPLC 极简可视化",
        "app_title": "HPLC 极简可视化",
        "app_subtitle": "上传您的 HPLC 数据，将自动渲染交互式折线图。",
        "upload_label": "请上传一个或多个 HPLC 数据文件 (CSV, CTX)",
        "example_data_title": "没有数据？可以先试用内置示例。",
        "load_examples_btn": "加载示例数据",
        "download_examples_btn": "下载示例 ZIP",
        "clear_files_btn": "🧹 一键清空所有导入文件",
        "imported_files": "### 已导入文件",
        "remove_file_help": "从本次绘图中移除",
        "parse_error": "解析文件前置发生错误: {}",
        "plot_error": "处理文件时发生错误: {}",
        "ctx_no_numeric_data": "CTX 文件中未找到可用的两列数值数据。",
        "multiple_signals_found": "在 **{}** 中检测到 {} 条曲线。请确认需要绘制哪些信号；检测器类型仅根据列名推测。",
        "signal_select": "选择 {} 中的信号",
        "signal_uv_hint": "推测：UV/DAD 信号",
        "signal_ms_hint": "推测：质谱 TIC/EIC 信号",
        "signal_unknown_hint": "检测器类型未知",
        "signal_dialog_title": "选择要导入的检测器信号",
        "signal_dialog_intro": "检测到 {} 个包含多条曲线的文件。请先选择要绘制的信号；检测器类型仅根据列名推测。",
        "signal_select_all": "全部导入",
        "signal_select_uv": "仅 UV/DAD",
        "signal_select_ms": "仅质谱",
        "signal_confirm_import": "确认并绘图",
        "signal_reselect": "重新选择检测器信号",
        "signal_mixed_recommendation": "当前绘图会把所有曲线放在同一坐标系中。为避免 UV/DAD 与质谱量级差异导致曲线难以阅读，建议一次只导入同一类信号。",
        "drag_to_reorder": "按住卡片上下拖动即可调整曲线顺序。",
        "manage_curves": "重命名或移除曲线",
        "curve_name_label": "曲线名称",
        "curve_name_duplicate": "“{}”已被使用，请换一个名称。",
        "diagnostic_title": "导入诊断信息",
        "diagnostic_intro": "这里显示程序实际识别到的内容，可用于判断时间列、信号类型和数据完整性是否正常。检测器类型仅根据列名推测。",
        "diagnostic_curve": "曲线",
        "diagnostic_detector": "推测信号",
        "diagnostic_columns": "原始列名",
        "diagnostic_points": "有效点数",
        "diagnostic_time_range": "时间范围",
        "diagnostic_skipped": "跳过行数",
        "diagnostic_duplicates": "重复时间点",
        "diagnostic_monotonic": "时间递增",
        "diagnostic_format": "格式 / 编码 / 分隔符",
        "diagnostic_yes": "是",
        "diagnostic_no": "否",
        "exit_app_btn": "关闭本地程序",
        "exit_app_help": "停止本地服务；关闭浏览器页面后程序也会自动退出。",
        "exit_app_closing": "本地程序正在关闭，现在可以关闭此页面。",
        
        "sidebar_header": "🎨 论文排版设置",
        "lang_title": "🌐 语言 / Language",
        "palette_title": "##### 1. 选择全局配色包",
        "palette_select": "自动为多条曲线分配颜色",
        "y_offset_title": "##### 2. Y轴错开堆叠 (Waterfall)",
        "y_offset_check": "启用均匀错开 (防止曲线重叠)",
        "y_offset_input": "堆叠间距 (Y-Offset)",
        "line_width_title": "##### 3. 设置全局线条粗细",
        "line_width_slider": "统一调节线宽",
        "display_settings_title": "##### 4. 辅助显示设置",
        "show_legend": "在图表中显示注释图例",
        "show_y_axis": "显示 Y 轴及刻度",
        "sample_label_position": "样品名显示位置",
        "sample_label_none": "不在曲线上显示",
        "sample_label_left": "显示在线左端",
        "sample_label_right": "显示在线右端",
        "sample_label_font_size": "样品名字号",
        "x_range_slider": "裁剪/缩放时间轴 (X轴范围)",
        "plot_width_mode": "图幅宽度",
        "plot_width_auto": "按时间范围自动调整",
        "plot_width_stretch": "铺满页面",
        "plot_width_custom": "自定义",
        "plot_width_custom_value": "自定义宽度 (px)",
        "interaction_title": "##### 5. 交互与标记 (点击/框选)",
        "sidebar_colored_title": "**🖌️ 已染色的峰面积:**",
        "clear_colors_btn": "🧹 清除所有染色",
        "delete_btn": "🗑️",
        "clear_marks_btn": "🧹 清除所有标记线",
        "view_raw_data": "查看 {} 原始数据",
        "download_svg_btn": "⬇ 下载 SVG 矢量图",
        "footer_made_by": "Made by 拒绝峰型拖尾、只想早点下班的小J",
        "footer_support": "👍 觉得好用？",
        "axis_time": "Time (min)",
        "axis_intensity": "Intensity"
    },
    "en": {
        "page_title": "HPLC Minimalist Plot",
        "app_title": "HPLC Minimalist Plot",
        "app_subtitle": "Upload your HPLC data to automatically render an interactive line chart.",
        "upload_label": "Upload one or more HPLC data files (CSV, CTX)",
        "example_data_title": "No data yet? Try the built-in examples.",
        "load_examples_btn": "Load example data",
        "download_examples_btn": "Download example ZIP",
        "clear_files_btn": "🧹 Clear all imported files",
        "imported_files": "### Imported Files",
        "remove_file_help": "Remove from this plot",
        "parse_error": "Error during file parsing: {}",
        "plot_error": "Error during plot rendering: {}",
        "ctx_no_numeric_data": "No usable two-column numeric data was found in the CTX file.",
        "multiple_signals_found": "Detected multiple signals in **{}** ({} total). Select the signals to plot; detector types are inferred from column names only.",
        "signal_select": "Select signals from {}",
        "signal_uv_hint": "Likely UV/DAD signal",
        "signal_ms_hint": "Likely MS TIC/EIC signal",
        "signal_unknown_hint": "Unknown detector type",
        "signal_dialog_title": "Choose detector signals to import",
        "signal_dialog_intro": "Detected {} files containing multiple signals. Select the signals to plot first; detector types are inferred from column names only.",
        "signal_select_all": "Import all",
        "signal_select_uv": "UV/DAD only",
        "signal_select_ms": "MS only",
        "signal_confirm_import": "Confirm and plot",
        "signal_reselect": "Choose detector signals again",
        "signal_mixed_recommendation": "The current plot uses one coordinate system for every curve. To avoid UV/DAD and MS scale differences obscuring signals, importing one detector type at a time is recommended.",
        "drag_to_reorder": "Drag the cards up or down to reorder the curves.",
        "manage_curves": "Rename or remove curves",
        "curve_name_label": "Curve name",
        "curve_name_duplicate": "“{}” is already in use. Choose another name.",
        "diagnostic_title": "Import diagnostics",
        "diagnostic_intro": "This shows what the app actually recognized so you can verify the time column, signal type, and data integrity. Detector types are inferred from column names only.",
        "diagnostic_curve": "Curve",
        "diagnostic_detector": "Likely signal",
        "diagnostic_columns": "Source columns",
        "diagnostic_points": "Valid points",
        "diagnostic_time_range": "Time range",
        "diagnostic_skipped": "Skipped rows",
        "diagnostic_duplicates": "Duplicate times",
        "diagnostic_monotonic": "Time ascending",
        "diagnostic_format": "Format / encoding / delimiter",
        "diagnostic_yes": "Yes",
        "diagnostic_no": "No",
        "exit_app_btn": "Close local app",
        "exit_app_help": "Stop the local service. It also exits automatically after the browser tab is closed.",
        "exit_app_closing": "The local app is closing. You can close this tab now.",
        
        "sidebar_header": "🎨 Publication Styling",
        "lang_title": "🌐 Language",
        "palette_title": "##### 1. Global Color Palette",
        "palette_select": "Auto-assign colors for multiple curves",
        "y_offset_title": "##### 2. Y-Axis Stacking (Waterfall)",
        "y_offset_check": "Enable even spacing (prevent overlapping)",
        "y_offset_input": "Stacking Spacing (Y-Offset)",
        "line_width_title": "##### 3. Global Line Width",
        "line_width_slider": "Adjust line width uniformly",
        "display_settings_title": "##### 4. Display Settings",
        "show_legend": "Show legend in the chart",
        "show_y_axis": "Show Y-axis and ticks",
        "sample_label_position": "Sample name position",
        "sample_label_none": "Do not show on curves",
        "sample_label_left": "Show at left edge",
        "sample_label_right": "Show at right edge",
        "sample_label_font_size": "Sample name font size",
        "x_range_slider": "Crop/Zoom Timeline (X-Axis Range)",
        "plot_width_mode": "Figure width",
        "plot_width_auto": "Auto by time range",
        "plot_width_stretch": "Fill page width",
        "plot_width_custom": "Custom",
        "plot_width_custom_value": "Custom width (px)",
        "interaction_title": "##### 5. Interaction & Marking (Click/Box)",
        "sidebar_colored_title": "**🖌️ Colored Peak Areas:**",
        "clear_colors_btn": "🧹 Clear all colors",
        "delete_btn": "🗑️",
        "clear_marks_btn": "🧹 Clear all marked lines",
        "view_raw_data": "View raw data for {}",
        "download_svg_btn": "⬇ Download SVG figure",
        "footer_made_by": "Made by J, fleeing the lab exactly on time.",
        "footer_support": "👍 Like this tool?",
        "axis_time": "Time (min)",
        "axis_intensity": "Intensity"
    },
    "jp": {
        "page_title": "HPLC シンプル可視化",
        "app_title": "HPLC シンプル可視化",
        "app_subtitle": "HPLCデータをアップロードすると、インタラクティブな折れ线グラフが自动的に描画されます。",
        "upload_label": "HPLCデータファイル（CSV, CTX）をアップロードしてください",
        "example_data_title": "データがない場合は、内蔵サンプルを試せます。",
        "load_examples_btn": "サンプルデータを読み込む",
        "download_examples_btn": "サンプル ZIP をダウンロード",
        "clear_files_btn": "🧹 すべてのインポートファイルをクリア",
        "imported_files": "### インポート済みのファイル",
        "remove_file_help": "このプロットから削除",
        "parse_error": "ファイルの解析中にエラーが発生しました: {}",
        "plot_error": "プロットの描画中にエラーが発生しました: {}",
        "ctx_no_numeric_data": "CTX ファイルに使用可能な2列の数値データが見つかりませんでした。",
        "multiple_signals_found": "**{}** から {} 本の信号を検出しました。描画する信号を選択してください。検出器タイプは列名からの推定です。",
        "signal_select": "{} の信号を選択",
        "signal_uv_hint": "推定：UV/DAD 信号",
        "signal_ms_hint": "推定：質量分析 TIC/EIC 信号",
        "signal_unknown_hint": "検出器タイプ不明",
        "signal_dialog_title": "インポートする検出器信号を選択",
        "signal_dialog_intro": "複数の信号を含むファイルを {} 個検出しました。先に描画する信号を選択してください。検出器タイプは列名からの推定です。",
        "signal_select_all": "すべてインポート",
        "signal_select_uv": "UV/DAD のみ",
        "signal_select_ms": "質量分析のみ",
        "signal_confirm_import": "確定して描画",
        "signal_reselect": "検出器信号を再選択",
        "signal_mixed_recommendation": "現在のプロットはすべての曲線に同じ座標系を使用します。UV/DAD と MS のスケール差で信号が見づらくならないよう、同じ種類の信号を一度に読み込むことを推奨します。",
        "drag_to_reorder": "カードを上下にドラッグして曲線の順序を変更できます。",
        "manage_curves": "曲線名の変更・削除",
        "curve_name_label": "曲線名",
        "curve_name_duplicate": "「{}」は使用済みです。別の名前を指定してください。",
        "diagnostic_title": "インポート診断",
        "diagnostic_intro": "時間列、信号タイプ、データの完全性を確認するため、アプリが認識した内容を表示します。検出器タイプは列名からの推定です。",
        "diagnostic_curve": "曲線",
        "diagnostic_detector": "推定信号",
        "diagnostic_columns": "元の列名",
        "diagnostic_points": "有効点数",
        "diagnostic_time_range": "時間範囲",
        "diagnostic_skipped": "スキップ行",
        "diagnostic_duplicates": "重複時間点",
        "diagnostic_monotonic": "時間昇順",
        "diagnostic_format": "形式 / 文字コード / 区切り",
        "diagnostic_yes": "はい",
        "diagnostic_no": "いいえ",
        "exit_app_btn": "ローカルアプリを終了",
        "exit_app_help": "ローカルサービスを停止します。ブラウザのタブを閉じた場合も自動的に終了します。",
        "exit_app_closing": "ローカルアプリを終了しています。このタブを閉じても構いません。",
        
        "sidebar_header": "🎨 论文フォーマット设定",
        "lang_title": "🌐 言语 / Language",
        "palette_title": "##### 1. グローバルカラーパレット",
        "palette_select": "复数の曲线に色を自动割り当て",
        "y_offset_title": "##### 2. Y轴のスタッキング",
        "y_offset_check": "均等な间隔を有効にする（重なりを防止）",
        "y_offset_input": "スタッキング间隔（Y-オフセット）",
        "line_width_title": "##### 3. グローバル线の太さ",
        "line_width_slider": "线の太さを均一に调整",
        "display_settings_title": "##### 4. 表示设定",
        "show_legend": "チャートに凡例を表示する",
        "show_y_axis": "Y轴と目盛りを表示する",
        "sample_label_position": "サンプル名の表示位置",
        "sample_label_none": "曲線上に表示しない",
        "sample_label_left": "左端に表示",
        "sample_label_right": "右端に表示",
        "sample_label_font_size": "サンプル名の文字サイズ",
        "x_range_slider": "タイムラインのトリミング/ズーム（X轴の范囲）",
        "plot_width_mode": "図の幅",
        "plot_width_auto": "時間範囲に合わせて自動調整",
        "plot_width_stretch": "ページ幅いっぱい",
        "plot_width_custom": "カスタム",
        "plot_width_custom_value": "カスタム幅 (px)",
        "interaction_title": "##### 5. インタラクション (クリック/ドラッグ)",
        "sidebar_colored_title": "**🖌️ 着色されたピーク面積:**",
        "clear_colors_btn": "🧹 すべての着色をクリア",
        "delete_btn": "🗑️",
        "clear_marks_btn": "🧹 すべてのマークされた線をクリア",
        "view_raw_data": "{} の生データを表示",
        "download_svg_btn": "⬇ SVG 図をダウンロード",
        "footer_made_by": "定時退社を全力で夢見るKより",
        "footer_support": "👍 気に入りましたか？",
        "axis_time": "Time (min)",
        "axis_intensity": "Intensity"
    }
}

def get_text(lang, key, *args):
    text = TRANSLATIONS.get(lang, TRANSLATIONS["zh"]).get(key, key)
    if args:
        return text.format(*args)
    return text
